version: '3.1'

services:
  db:
    image: postgres 
    restart: always
    volumes:
      - /tmp/postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
  app:
    image: patients
    build:
      context: .
    entrypoint: bin/entrypoint.sh
    restart: always
    environment:
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
    ports:
      - 80:3001
    links:
      - "db:database"
